### ISSUE TITLE
Feature Request: Notifications on recipient data extraction 

### ISSUE THREAD

**Issue by GH34569873** [oxen-io/session-ios#155]
I am wondering if there would be a way to add a feature where the sender, in a P2P/Group conversation, could be alerted if a recipient of a message took a ScreenShot, Copy/Pasted text etc...? This would not need to be a push notification, just something within the app alerting the sender. 

I know Wickr has this functionality, but being as I am not a dev, I’m not sure how difficult this would be to implement. 

Thank you for this great project and keep up the wonderful work!

**Comment by nielsandriesse** [comment]
We definitely can and will do this :)

**Comment by eharris** [comment]
I think this is kind of a useless feature, as you can always take a picture of the screen with another device, and there is no way to detect that.  However I'm not against it as long as there is an option to disallow this notification on a per-conversation basis (so that other members of the conversation are aware of that setting so they can choose whether they want to participate).

**Comment by nielsandriesse** [comment]
Even though it's true that this doesn't protect against someone taking a photo of your screen. It does add * some * protection, and it's an often requested feature as well. We've implemented this now and will be shipping it soon!
