### ISSUE TITLE
Allow users to set nicknames.

### ISSUE THREAD

**Issue by Mikunj** [oxen-io/session-ios#21]
In the desktop application we allow the users to set the nickname of their contacts.
By default this nickname is preferred over the users display name which is preferred over their pub key.

The user pub key should also be shown while nickname or display name is being shown.

**Comment by eharris** [comment]
I think this is a critical issue that needs to be addressed.  I want to identify conversations how *I* want to, not how the other person decides they want to be called (which is often just a random moniker anyway).  And what happens when multiple people have used the same name?  Or someone who is friends in common with someone else trying to play a trick and make you send something to the wrong person by setting their name the same as someone else?

**Comment by nielsandriesse** [comment]
This is on our roadmap.

**Comment by nielsandriesse** [comment]
This is now implemented and will be part of the next release!
