### ISSUE TITLE
the deleted messages are never deleted

### ISSUE THREAD

**Issue by gilojimjim** [oxen-io/session-ios#373]
The deleted messages in the signal.db database are NEVER deleted. they are marked deleted but are always stored in the signal.db (the database is still growing)

you should use the sqlite VACUUM command each time Session is run, to delete the old messages in the database.

https://sqlite.org/lang_vacuum.html

**Comment by M09NST3R** [comment]
Not cool.

**Comment by nielsandriesse** [comment]
This shouldn't be the case. When the database is created we set `PRAGMA auto_vacuum = FULL`, which should auto-vacuum the database as needed. I'll additionally vacuum the database every time the app is started just to be sure.

Did you come to the conclusion that messages aren't deleted just by the fact that the database keeps growing? Because that could be due to something other than message storage.

**Comment by nielsandriesse** [comment]
Closing this as we now not only have `PRAGMA auto_vacuum = FULL` set, but we * also * manually vacuum on launch
