### ISSUE TITLE
[BUG] Database error after offload and reinstall

### ISSUE THREAD

**Issue by shivaprsd** [oxen-io/session-ios#935]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following error occurs **at startup** (see screenshot)

![B2EB2829-8782-442B-A749-341211BC086E](https://github.com/oxen-io/session-ios/assets/18247990/14327770-abf6-43f6-a7d9-9122e9db0e2b)

### Expected Behavior

The app should open and restore my chats from the database.

### Steps To Reproduce

1. **Offload** the app via iOS Storage settings.
2. Reinstall from the App Store.
3. Open the app.

### iOS Version

iOS 15.7.9

### Session Version

2.4.1 (424)

### Anything else?

Exported application logs:
[com.loki-project.loki-messenger 2023-10-23--10-22-19-560.log](https://github.com/oxen-io/session-ios/files/13111078/com.loki-project.loki-messenger.2023-10-23--10-22-19-560.log)

**Comment by aSeniyants** [comment]
The same issue

**Comment by mpretty-cyro** [comment]
@shivaprsd looking at your logs the issue was caused by a migration problem introduced in `2.4.1` which was fixed in `2.4.2` - if you update to the latest version it _should_ just work (let me know if not)

@aSeniyants Do you know which version you are running or are you able to share the exported logs via the `Export Logs` button on the modal which appears?

**Comment by shivaprsd** [comment]
@mpretty-cyro Thanks for the head up. Update solved the issue!
